apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: openstackcontrollers.controller.openstack.org
spec:
  group: controller.openstack.org
  names:
    kind: OpenStackController
    listKind: OpenStackControllerList
    plural: openstackcontrollers
    singular: openstackcontroller
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: true
    storage: true
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          description: Metadata definition for the ServiceTelemetry object
          type: object
        spec:
          description: Specification of the desired behavior of the Service Telemetry Operator.
          properties:
            size:
              description: Number of controllers to instantiate
              type: integer
        status:
          description: Status results of an instance of Service Telemetry
          properties:
            conditions:
              description: The resulting conditions when a Service Telemetry is instantiated
              items:
                properties:
                  status:
                    type: string
                  type:
                    type: string
                  reason:
                    type: string
                  lastTransitionTime:
                    type: string
                type: object
              type: array
          type: object
