apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: openstackcontrollers.controller.openstack.org
spec:
  group: controller.openstack.org
  names:
    kind: OpenStackController
    listKind: OpenStackControllerList
    plural: openstackcontrollers
    singular: openstackcontroller
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
