apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "controller.openstack.org/v1alpha1",
          "kind": "OpenStackController",
          "metadata": {
            "name": "openstack-cloud"
          },
          "spec": {
            "size": 3
          }
        }
      ]
    capabilities: Basic Install
    categories: cloud
    certified: "false"
    containerImage: quay.io/leifmadsen/openstack-controller-operator:latest
  name: openstack-controller-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Represents an OpenStack Controller object
      displayName: OpenStack Controller
      kind: OpenStackController
      name: openstackcontroller.controller.openstack.org
      resources:
      - kind: Pod
        name: ""
        version: v1
      - kind: Deployments
        name: ""
        version: v1
      - kind: ReplicaSets
        name: ""
        version: v1
      - kind: Services
        name: ""
        version: v1
      - kind: ConfigMaps
        name: ""
        version: v1
      - kind: OpenStackControllers
        name: ""
        version: v1alpha1
      specDescriptors:
      - description: Number of Controller instances to deploy
        displayName: Size
        path: size
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:number
      statusDescriptors:
      - description: Conditions provided by deployment
        displayName: Conditions
        path: conditions
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes.conditions
      version: v1alpha1
  description: Placeholder description
  displayName: Openstack Controller Operator
  install:
    spec:
      deployments:
      - name: openstack-controller-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: openstack-controller-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: openstack-controller-operator
            spec:
              containers:
              - command:
                - /usr/local/bin/ao-logs
                - /tmp/ansible-operator/runner
                - stdout
                image: quay.io/leifmadsen/openstack-controller-operator:latest
                imagePullPolicy: Always
                name: ansible
                resources: {}
                volumeMounts:
                - mountPath: /tmp/ansible-operator/runner
                  name: runner
                  readOnly: true
              - env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: openstack-controller-operator
                - name: ANSIBLE_GATHERING
                  value: explicit
                image: quay.io/leifmadsen/openstack-controller-operator:latest
                imagePullPolicy: Always
                name: operator
                resources: {}
                volumeMounts:
                - mountPath: /tmp/ansible-operator/runner
                  name: runner
              serviceAccountName: openstack-controller-operator
              volumes:
              - emptyDir: {}
                name: runner
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - openstack-controller-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - get
        - apiGroups:
          - controller.openstack.org
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: openstack-controller-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - openstack
  maintainers:
  - email: leif@redhat.com
    name: Leif Madsen
  maturity: alpha
  provider:
    name: Red Hat
  version: 0.0.1
